### ISSUE TITLE
Question - Any instability from left over services between tests?

### ISSUE THREAD

**Issue by mattcmf** [sebaslogen/CleanGUITestArchitecture#11]
Hi,

Great repository, just had a quick question. Have you found any instability when working with killing activities outside the standard workflow?
E.g. managing the app life cycle via @TestRule @Test approach used by the standard Android Test Runner?

Specifically: ActivityFinisher.finishOpenActivities(); // Required for testing App with multiple activities

Full details:
https://jabknowsnothing.wordpress.com/2015/11/05/activitytestrule-espressos-test-lifecycle/

Cheers!

**Comment by sebaslogen** [comment]
The @TestRule has worked just fine in all projects I used, but to be honest, I still use the ActivityInstrumentationTestCase2 in my daily work project, because there was no big incentive to change it, it just works and we never modify that code.

The need for ActivityFinisher comes from larger projects, where you need to test interactions between screens (mostly flows across Activities). This kind of test scenarios can leave a trail of opened activities depending on which mode new activities are launched. Since this should not be a dependency for starting a new test scenario with a clean state, ActivityFinisher ensures this requirement is fulfilled.
